# Configuração do Banco de Dados PostgreSQL (mesmo banco 'mytest' que usamos no ETL)
spring.datasource.url=jdbc:postgresql://localhost:5432/mytest
spring.datasource.username=postgres
spring.datasource.password=admin1234
# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Porta em que a API vai rodar
server.port=${PORT:8080}
logging.level.org.springframework.web=DEBUG